### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module at wrapSafe (internal/modules/cjs/loader.js:1117:16)

### ISSUE THREAD

**Issue by eonward** [nandorojo/dripsy#27]
Hi hi

I'm getting this error at build in a clean project bootstrapped with Expo + NextJS... 💦 

```
import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1117:16)
    at Module._compile (internal/modules/cjs/loader.js:1165:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)

    at Object.<anonymous> (/mnt/c/Users/Eon/dev/dripsy/e10-app/node_modules/dripsy/lib/commonjs/css/index.js:1:958)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)

    at Object.<anonymous> (/mnt/c/Users/Eon/dev/dripsy/e10-app/node_modules/dripsy/lib/commonjs/css/create-native-themed-component.js:1:492)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
```

Any thoughts? 🤔 

Here's my package:
```
{
  "name": "dripsy-test",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "next",
    "eject-next": "next-expo customize",
    "eject": "expo eject"
  },
  "dependencies": {
    "dripsy": "^0.5.2",
    "expo": "~37.0.3",
    "next": "^9.5.2",
    "next-compose-plugins": "^2.2.0",
    "next-transpile-modules": "^4.1.0",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
    "react-native-web": "~0.12.0"
  },
  "devDependencies": {
    "@expo/next-adapter": "^2.1.25"
  },
  "resolutions": {
    "@theme-ui/core": "0.4.0-rc.1",
    "@theme-ui/css": "0.4.0-rc.1",
    "@theme-ui/mdx": "0.4.0-rc.1"
  }
}
```

The resolutions are there as a temporary workaround to issue #26 as theme-ui is broken as of this writing. 🦑

Nando: Amazing project! Thank you 🍷 🍷

**Comment by 509dave16** [comment]
@nandorojo I am also facing this issue. @eonward37 What part of your config was originally messed up? We're using React Native Web with Razzle. And even though I added dripsy to our webpack rule for processing node_modules that need to be transpiled:
```
// Process react-native modules because node needs commonjs
      {
        test: /((@?react-(navigation|native))|dripsy).*\.(ts|js)x?$/,
        exclude: [
          /react-native-web/,
          /\.(native|ios|android)\.(ts|js)x?$/
        ],
        loader: 'babel-loader',
      },
```

I'm still getting the following error:
```
✔ Client
  Compiled successfully in 6.47s
✔ Server
  Compiled successfully in 3.64s
/Users/david/Projects/theseus/node_modules/react-native/index.js:13
import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
       ^^^^^^
SyntaxError: Unexpected token typeof
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/david/Projects/theseus/node_modules/dripsy/lib/commonjs/css/index.tsx:11:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

Any suggestions or hints would be much appreciated :) ! And I can provide the full `razzle.config.js` if that helps as well.

**Comment by nandorojo** [comment]
@509dave16 did you try the workaround from https://github.com/nandorojo/dripsy/issues/26?

**Comment by 509dave16** [comment]
@nandorojo I gave the workaround a shot, rebuilding my node_modules before running a razzle server again. Didn't resolve the error. Appreciate you giving this a look over. Don't worry about spending any more time on this. Just thought you might have encountered this before and had a good idea of what direction pursue. I will think on your update regarding React Native Web more ;)

**Comment by nandorojo** [comment]
Sounds good. I'm more of a fan of Nextjs, so I've spent my time there with Dripsy. Good luck!

**Comment by 509dave16** [comment]
@nandorojo Thank you! We currently have Razzle on trial for our rebuild and if it gives us any more significant issues then we'll be transitioning to Next.js :)
